// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZLWpxrCtjv7HWAM75egtHWrDnr7owJPk',
    appId: '1:107455410788:web:7278d8bd90afa7af6ba571',
    messagingSenderId: '107455410788',
    projectId: 'okada-457703',
    authDomain: 'okada-457703.firebaseapp.com',
    storageBucket: 'okada-457703.firebasestorage.app',
    measurementId: 'G-B43D2SJ0ZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALnxWNx0PUkOc0lPVwMd2xKrOfTmZS9Tw',
    appId: '1:107455410788:android:994f69a77a640ca56ba571',
    messagingSenderId: '107455410788',
    projectId: 'okada-457703',
    storageBucket: 'okada-457703.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzwFGDxbjWvLav0b8d_R3icThNoL3WbiE',
    appId: '1:107455410788:ios:af84765b9feea8266ba571',
    messagingSenderId: '107455410788',
    projectId: 'okada-457703',
    storageBucket: 'okada-457703.firebasestorage.app',
    iosBundleId: 'com.amagyei.okada.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzwFGDxbjWvLav0b8d_R3icThNoL3WbiE',
    appId: '1:107455410788:ios:3a9ef1fd2933d9f16ba571',
    messagingSenderId: '107455410788',
    projectId: 'okada-457703',
    storageBucket: 'okada-457703.firebasestorage.app',
    iosBundleId: 'com.example.okadaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZLWpxrCtjv7HWAM75egtHWrDnr7owJPk',
    appId: '1:107455410788:web:db0d1a57ae8b50466ba571',
    messagingSenderId: '107455410788',
    projectId: 'okada-457703',
    authDomain: 'okada-457703.firebaseapp.com',
    storageBucket: 'okada-457703.firebasestorage.app',
    measurementId: 'G-B4NJ9GGETY',
  );
}
